python train.py \
    --model_name_or_path llama_finetuned \
    --meta_file_path /home/tonyzst/Desktop/CS229-Project/data/MMTrail/train/metas_video_audio_convs.json \
    --data_folder /home/tonyzst/Desktop/CS229-Project/data/MMTrail/train \
    --output_dir /home/tonyzst/Desktop/CS229-Project/ \
    --is_multimodal \
    --has_image \
    --has_audio \
    --stage stage_3 \
    --batch_size 1 \
    --num_train_epochs 10 \
    --learning_rate 1e-5 \
    --logging_steps 50 \
    --fp16 True \
    --deepspeed_config deepspeed.json \
    --model_save_path ./llama_finetuned \
    --max_token_length 1024