name: project
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - cuda-toolkit
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - transformers
  - ipykernel
  - psutil
  - protobuf
