name: cs229-cogvlm2-llama3-caption
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - pip
  - python=3.8
  - pytorchvideo==0.1.5
  - transformers==4.42.4
  - pillow
  - pydantic>=2.7.1
  - timm>=0.9.16
  - openai>=1.30.1
  - loguru>=0.7.2
  - pydantic>=2.7.1
  - einops
  - sse-starlette>=2.1.0
  - flask
  # - gunicorn
  - gevent
  - requests
  - gradio
  - pip:
      # - decord>=0.6.0
      - torch==2.1.0
      - torchvision==0.16.0
      - huggingface-hub>=0.23.0
      - chainlit>=1.0
      - xformers
# prefix: /home/sabrina/anaconda3/envs/cs229-cogvlm2-llama3-caption